# Generated by Django 5.2.1 on 2025-06-02 09:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profiles',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='usertype',
            new_name='user_type',
        ),
    ]
